source 'https://rubygems.org'

gem 'bullet', '4.6.0'

gem 'rails', '4.0.0'
gem 'mysql2', '0.3.13'

gem 'sass-rails', '4.0.0'
gem 'uglifier', '1.3.0'
gem 'coffee-rails', '4.0.0'
gem 'jquery-rails', '3.0.4'
gem 'haml-rails', '0.4.0'
# gem 'hamlbars', '2.0.1'
gem 'ember-rails', '0.13.0'
gem 'ember-source', '1.0.0.rc6.4'
gem 'google-analytics-rails', '0.0.4'

gem 'thor', '0.18.1'
gem 'progress_bar', '1.0.0'

gem 'paperclip', github: 'thoughtbot/paperclip'
# Update this when aws-sdk isn't stupid about
# nokogiri 1.6/ruby 1.9.3 support
gem 'aws-sdk', '1.11.1'

#search
gem 'sunspot_solr', github: 'sunspot/sunspot', branch: 'master'
gem 'sunspot_rails', github: 'sunspot/sunspot', branch: 'master'

gem "acts-as-taggable-on", "~> 2.4.1"

# Parsing
gem 'nokogiri', "1.6.0"
gem 'embedly', "1.8.0"

# API
gem 'active_model_serializers', '0.8.1'
gem "rails-api", github: 'rails-api/rails-api'

#view
gem 'haml', '3.1.7'
gem 'less-rails', '2.3.3'
gem 'therubyracer', '0.11.4'

# ActiveAdmin setup - Re-evaluate when it gets rails 4 gem
gem 'devise', '3.2'
gem 'omniauth', '1.1.4'
gem 'omniauth-twitter'
gem 'activeadmin', github: 'gregbell/active_admin'

# Use unicorn as the app server
# gem 'unicorn'
group :development do
  gem 'foreman', '0.63.0'
  gem 'quiet_assets', '1.0.2'
end

group :development, :test do
  gem 'rspec-rails', '2.14.0'
  gem 'pry', '0.9.12.2'
  gem 'pry-remote', '0.1.7'
  gem 'fabrication', '2.7.2'
  # Use Capistrano for deployment
  gem 'capistrano', '2.15.4'
  gem 'capistrano-ext'
  gem 'caplock'
  gem 'faker', '1.2.0'
end

group :test do
  # gem 'cucumber-rails', '1.3.1', :require => false
  # No gem for rails 4 support yet 7/29/13 - Jared
  gem 'launchy', '2.3.0'
  gem 'birdbath', '1.3.5'
  gem 'cucumber-rails', :require => false, :git => 'https://github.com/cucumber/cucumber-rails.git', :branch => 'master_rails4_test'
  gem 'cucumber', '1.3.2'
  gem 'capybara', '2.1.0'
  gem 'capybara-webkit', '1.0.0'
  gem 'capybara-screenshot', '0.3.13'
  gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'
  gem 'database_cleaner', '1.1.1'
  gem 'sunspot_test', '0.4.0'
  gem 'fire_poll', '1.2.0'
end

group :assets do
  gem 'handlebars_assets'
end
